version: "3"

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --log-bin=ROW
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
    networks:
      - ncloud_int

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - "${DATA_DIR}/redis:/data"
    expose:
      - 6379
    networks:
      - ncloud_int

  app:
    image: nextcloud:latest
    restart: always
    networks:
      - ncloud_int
      - traefik
      - ldap
    volumes:
      - ${DATA_DIR}/app/html:/var/www/html
      - ${DATA_DIR}/app/config:/var/www/html/config
      - ${DATA_DIR}/app/data:/var/www/html/data
      - ${DATA_DIR}/app/custom_apps:/var/www/html/custom_apps
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=${DOMAINNAME} app
      - TRUSTED_PROXIES=${NEXTCLOUD_SUBNET} ${TRAEFIK_SUBNET}
      - OVERWRITEHOST=cloud.${DOMAINNAME}
      - OVERWRITEPROTOCOL=https
      - MYSQL_HOST=db
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - NEXTCLOUD_ADMIN_PASSWORD
      - NEXTCLOUD_ADMIN_USER
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.priority=1
      - traefik.http.routers.nextcloud.entrypoints=websecure
      - traefik.http.routers.nextcloud.rule=Host(`cloud.${DOMAINNAME}`)
      - traefik.http.routers.nextcloud.middlewares=nextcloud-redirregex,secheader@file
      - traefik.http.routers.nextcloud.tls=true
      - traefik.http.routers.nextcloud.tls.certresolver=myresolver
      - traefik.http.middlewares.nextcloud-redirregex.redirectregex.permanent=true
      - "traefik.http.middlewares.nextcloud-redirregex.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-redirregex.redirectregex.replacement=https://$${1}/remote.php/dav/"

  cron:
    image: nextcloud:latest
    restart: always
    networks:
      - ncloud_int
    depends_on:
      - db
      - redis
    volumes:
      - ${DATA_DIR}/app/html:/var/www/html
      - ${DATA_DIR}/app/config:/var/www/html/config
      - ${DATA_DIR}/app/data:/var/www/html/data
      - ${DATA_DIR}/app/custom_apps:/var/www/html/custom_apps
    entrypoint: /cron.sh

networks:
  traefik:
    external:
      name: traefik
  ldap:
    external:
      name: ldap
  ncloud_int:
    driver: bridge
    ipam:
      config:
        - subnet: ${NEXTCLOUD_SUBNET} # necessary for the notify_push <-> nextcloud traffic

