version: "3"

services:
  db:
    image: postgres:14
    restart: unless-stopped
    networks:
      - ncloud_int
    volumes:
      - ${VOLUMES_DIR}/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  redis:
    image: redis:6
    restart: unless-stopped
    volumes:
      - "${VOLUMES_DIR}/redis:/data"
    networks:
      - ncloud_int

  app:
    image: nextcloud:${NEXTCLOUD_VERSION}
    restart: unless-stopped
    networks:
      - ncloud_int
      - traefik
      - ldap
    volumes:
      - ${VOLUMES_DIR}/app/html:/var/www/html
      - ${VOLUMES_DIR}/app/config:/var/www/html/config
      - ${VOLUMES_DIR}/app/data:/var/www/html/data
      - ${VOLUMES_DIR}/app/custom_apps:/var/www/html/custom_apps
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=${DOMAINNAME} app
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD
      - TRUSTED_PROXIES=${NEXTCLOUD_SUBNET} ${TRAEFIK_SUBNET}
      - OVERWRITEHOST=cloud.${DOMAINNAME}
      - OVERWRITEPROTOCOL=https
      - POSTGRES_HOST=db:5432
      - REDIS_HOST=redis
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    depends_on:
      - db
      - redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.priority=1
      - traefik.http.routers.nextcloud.entrypoints=websecure
      - traefik.http.routers.nextcloud.rule=Host(`cloud.${DOMAINNAME}`)
      - traefik.http.routers.nextcloud.middlewares=nextcloud-redirregex,secheader@file
      - traefik.http.middlewares.nextcloud-redirregex.redirectregex.permanent=true
      - "traefik.http.middlewares.nextcloud-redirregex.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-redirregex.redirectregex.replacement=https://$${1}/remote.php/dav/"

  cron:
    image: nextcloud:${NEXTCLOUD_VERSION}
    restart: unless-stopped
    networks:
      - ncloud_int
    depends_on:
      - db
      - redis
    volumes:
      - ${VOLUMES_DIR}/app/html:/var/www/html
      - ${VOLUMES_DIR}/app/config:/var/www/html/config
      - ${VOLUMES_DIR}/app/data:/var/www/html/data
      - ${VOLUMES_DIR}/app/custom_apps:/var/www/html/custom_apps
    entrypoint: /cron.sh

networks:
  traefik:
    name: traefik
  ldap:
    name: ldap
  ncloud_int:
    driver: bridge
    ipam:
      config:
        - subnet: ${NEXTCLOUD_SUBNET} # necessary for the notify_push <-> nextcloud traffic

